name: Daily build
on:
  schedule:
    - cron: 0 0 * * * # Every day at midnight (UTC)
jobs:
  daily-build:
    runs-on: windows-latest
    strategy:
      matrix:
        rid: [linux-x64, win-x64, osx-x64]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        token: ${{ secrets.SUB_MODULE_TOKEN }}
        submodules: true

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore BeUtl.sln

    - name: Build
      run: dotnet publish ./src/BeUtl/BeUtl.csproj -c Release -r ${{matrix.rid}} --no-self-contained

    - name: Save
      uses: actions/upload-artifact@v2
      with:
        name: beutl_${{matrix.rid}}
        path: ./src/BeUtl/bin/Release/net6.0/${{matrix.rid}}/publish
