name: Daily build
on:
  schedule:
    - cron: 0 0 * * * # Every day at midnight (UTC)
jobs:
  daily-build:
    runs-on: windows-latest
    strategy:
      matrix:
        rid: [linux-x64, win-x64, osx-x64]
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Restore dependencies
      run: dotnet restore Beutl.sln

    - name: Build
      run: dotnet publish ./src/Beutl/Beutl.csproj -c Release -r ${{matrix.rid}} --no-self-contained

    - name: Save
      uses: actions/upload-artifact@v3
      with:
        name: beutl_${{matrix.rid}}
        path: ./src/Beutl/bin/Release/net7.0/${{matrix.rid}}/publish
